import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const Metropolis = localFont({
  src: [
    {
      path: "./fonts/Metropolis-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-ExtraLight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-Medium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-Regular.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-Bold.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/Metropolis-ExtraBold.otf",

      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-black.otf",
      weight: "900",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${Metropolis.className}`}>{children}</body>
    </html>
  );
}
